url=jdbc:postgresql://db:5432/mgdb_liquibase?currentSchema=public
username=postgres
password=postgres
driver=org.postgresql.Driver
changeLogFile=db/changelog/db.changelog-master.yaml
logLevel=info
defaultSchemaName=public
liquibaseSchemaName=liquibase
